import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './ExampleApp.css'

/** This is the original example code generated by default when creating a new React / Vite project. 
 * This was originally named "App." I left it in as "ExampleApp" so we could reference it while we're still learning. */

/** The example code is set up such that everything on the example page (index.html after being rendered in the browser) comes from this function.
 * What's basically happening is this:
 *    traditional web page content is built with HTML
 *    traditional web page CONTENT (not appearance) is static and does not change
 *    to make web page content dynamic and interactive, we need to dynamically adjust its content, which is done through JS and React
 *    
 *    React functions return pieces of HTML code (which cancontain bits of JavaScript as well)
 *    The HTML returned by those functions is imported to the HTML page as a script */
function ExampleApp() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/ExampleAppApp.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default ExampleApp
